# Numpy

In [34]:
import numpy as np # pacakage = library

In [36]:
np.__version__ #matrix is collection data structure and data structure is collection of data types 

'1.26.4'

In [38]:
import sys
sys.version

'3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 15:03:56) [MSC v.1929 64 bit (AMD64)]'

# Creating Arrays

In [41]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [43]:
type(my_list)

list

In [45]:
arr = np.array(my_list)

In [47]:
arr

array([0, 1, 2, 3, 4, 5])

In [49]:
type(arr)

numpy.ndarray

In [51]:
type(my_list)

list

In [53]:
np. # only learn import function

SyntaxError: invalid syntax (2191267563.py, line 1)

In [55]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [57]:
np.arange(0,19)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18])

In [59]:
np.arange(-10,10)

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9])

In [61]:
np.arange(-3,3)

array([-3, -2, -1,  0,  1,  2])

In [63]:
np.arange(-10,10,3)

array([-10,  -7,  -4,  -1,   2,   5,   8])

In [65]:
np.zeros(4)

array([0., 0., 0., 0.])

In [67]:
np.zeros(4, dtype=int)

array([0, 0, 0, 0])

In [69]:
np.ones(4, dtype=int)

array([1, 1, 1, 1])

In [71]:
zero = np.zeros([2,3])
print(zero)

print('####')

print(type(zero))

[[0. 0. 0.]
 [0. 0. 0.]]
####
<class 'numpy.ndarray'>


In [73]:
np.zeros([4,10])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [75]:
n = (5,9)
n1 = (1,10)
print(np.zeros(n))

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [77]:
np.ones(3)

array([1., 1., 1.])

In [79]:
np.ones([2,10])

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [81]:
np.ones(3, dtype=int)

array([1, 1, 1])

In [83]:
np.ones([2,7], dtype=int)

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]])

In [85]:
np.ones([3,3], dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

# range

In [88]:
range(17)

range(0, 17)

In [90]:
k = range(17)
k

range(0, 17)

In [92]:
list(k)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]

In [94]:
for i in k:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16


In [96]:
list(k)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]

# random

In [132]:
np.random.rand(4) # evry time gives a different numbers

array([0.7737585 , 0.02684285, 0.97747366, 0.54106999])

In [103]:
np.random.random(4)

array([0.9934214 , 0.34334596, 0.63393551, 0.59064763])

In [109]:
np.random.rand(1,5)

array([[0.91905051, 0.34780537, 0.81148382, 0.92289654, 0.15680043]])

In [117]:
np.random.rand(2,3,4) # 2 alyers 3 r 4 c

array([[[0.6361126 , 0.0336712 , 0.08741135, 0.52150343],
        [0.50466896, 0.50966914, 0.95627614, 0.65454943],
        [0.41250355, 0.21419242, 0.97316766, 0.17581094]],

       [[0.04469728, 0.51943753, 0.64087676, 0.17951947],
        [0.78717751, 0.80569654, 0.45977085, 0.83203367],
        [0.22237935, 0.36217951, 0.94978609, 0.50700025]]])

In [121]:
np.random.randint(1,20)

2

In [124]:
np.random.randint(1,20,3)

array([11,  9,  6])

In [130]:
np.random.randint(1,20,(3,4))

array([[ 6,  6,  3, 16],
       [ 5, 11,  4,  9],
       [15, 15, 11,  1]])

In [1]:
import numpy as np

In [3]:
np.__version__

'1.26.4'

In [5]:
import sys
sys.version

'3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 15:03:56) [MSC v.1929 64 bit (AMD64)]'

# creating arrays

In [8]:
mylist = [0,1,2,3,3,4,5]
mylist

[0, 1, 2, 3, 3, 4, 5]

In [10]:
type(mylist)

list

In [12]:
arr = np.array(mylist)

In [14]:
arr

array([0, 1, 2, 3, 3, 4, 5])

In [16]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [18]:
arr

array([0, 1, 2, 3, 3, 4, 5])

In [20]:
np.arange(3.0)

array([0., 1., 2.])

In [22]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [26]:
np.arange(-10,20)

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,
        16,  17,  18,  19])

In [28]:
np.arange(10,10)

array([], dtype=int32)

In [30]:
np.arange(10,20,4)

array([10, 14, 18])

In [32]:
np.arange(10,20,3,4)

TypeError: Cannot interpret '4' as a data type

In [36]:
a1 = np.zeros(4)
a1

array([0., 0., 0., 0.])

In [40]:
a1 = np.zeros(4, dtype=int)
a1

array([0, 0, 0, 0])

In [46]:
a1 = np.zeros((4,2))
a1

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [50]:
a1 = np.zeros((2,4))
a1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [52]:
n = (5,7)
n1 = (6,7)
print(np.zeros(n))

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [54]:
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [56]:
np.ones(4)

array([1., 1., 1., 1.])

In [58]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [62]:
np.ones((2,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [66]:
n

(5, 7)

In [68]:
np.ones(n)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [72]:
np.ones(n1,dtype= int)

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]])

In [78]:
from numpy import *
arange(3)

array([0, 1, 2])

In [86]:
range(12)
list(range(12))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [90]:
y = list(range(12))
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [92]:
np.

SyntaxError: invalid syntax (2469254449.py, line 1)

In [96]:
zeros(5) # from numpy import *

array([0., 0., 0., 0., 0.])

In [98]:
np.threes((3,2))

AttributeError: module 'numpy' has no attribute 'threes'

In [102]:
rand(3,2)
random.rand(3,2)

NameError: name 'rand' is not defined

In [104]:
np.random.rand(4)

array([0.09053989, 0.03105701, 0.61089715, 0.86090689])

In [108]:
np.random.rand(3,4)

array([[0.50328913, 0.58794995, 0.66926957, 0.79160718],
       [0.98925188, 0.66405714, 0.93982031, 0.50150113],
       [0.20961558, 0.33001339, 0.50566577, 0.79602367]])

In [112]:
np.random.rand(3,4,3)

array([[[0.0481952 , 0.49411829, 0.10942897],
        [0.17751668, 0.62506103, 0.62705718],
        [0.21882862, 0.36078673, 0.62368503],
        [0.8299662 , 0.0632641 , 0.84907019]],

       [[0.43491768, 0.14176514, 0.70190309],
        [0.43864872, 0.10017987, 0.40138478],
        [0.42324941, 0.36143151, 0.69078261],
        [0.82298086, 0.24658616, 0.80506578]],

       [[0.92978812, 0.5922283 , 0.99201852],
        [0.88991793, 0.68598595, 0.06685745],
        [0.51560712, 0.50439165, 0.67854881],
        [0.64652145, 0.33825419, 0.16060091]]])

In [116]:
np.random.randint(3,7,5)

array([6, 6, 3, 5, 6])

In [120]:
np.random.randint(1,100,5)

array([92, 19, 98, 56, 93])

In [134]:
np.random.randint(5)

4

In [136]:
np.random.randint(2,6,(3,5))

array([[2, 2, 5, 4, 4],
       [4, 3, 2, 2, 5],
       [5, 3, 3, 2, 4]])

In [138]:
np.random.randint(2,10,(4,5))

array([[9, 5, 2, 9, 7],
       [6, 2, 7, 8, 7],
       [2, 5, 6, 7, 2],
       [5, 6, 8, 3, 5]])

In [144]:
b = np.random.randint(2,10,(7,7))

In [146]:
b

array([[6, 8, 9, 6, 7, 7, 8],
       [7, 3, 6, 4, 5, 3, 9],
       [3, 7, 8, 9, 5, 3, 6],
       [7, 5, 9, 3, 3, 8, 2],
       [5, 3, 4, 3, 4, 9, 6],
       [8, 5, 8, 3, 4, 3, 3],
       [2, 6, 7, 4, 7, 3, 7]])

In [150]:
b[:]

array([[6, 8, 9, 6, 7, 7, 8],
       [7, 3, 6, 4, 5, 3, 9],
       [3, 7, 8, 9, 5, 3, 6],
       [7, 5, 9, 3, 3, 8, 2],
       [5, 3, 4, 3, 4, 9, 6],
       [8, 5, 8, 3, 4, 3, 3],
       [2, 6, 7, 4, 7, 3, 7]])

In [152]:
b[:4]

array([[6, 8, 9, 6, 7, 7, 8],
       [7, 3, 6, 4, 5, 3, 9],
       [3, 7, 8, 9, 5, 3, 6],
       [7, 5, 9, 3, 3, 8, 2]])

In [154]:
b[::-1]

array([[2, 6, 7, 4, 7, 3, 7],
       [8, 5, 8, 3, 4, 3, 3],
       [5, 3, 4, 3, 4, 9, 6],
       [7, 5, 9, 3, 3, 8, 2],
       [3, 7, 8, 9, 5, 3, 6],
       [7, 3, 6, 4, 5, 3, 9],
       [6, 8, 9, 6, 7, 7, 8]])

In [156]:
b[0:-1]

array([[6, 8, 9, 6, 7, 7, 8],
       [7, 3, 6, 4, 5, 3, 9],
       [3, 7, 8, 9, 5, 3, 6],
       [7, 5, 9, 3, 3, 8, 2],
       [5, 3, 4, 3, 4, 9, 6],
       [8, 5, 8, 3, 4, 3, 3]])

In [170]:
b[-4]

array([7, 5, 9, 3, 3, 8, 2])

In [172]:
b[::-4]

array([[2, 6, 7, 4, 7, 3, 7],
       [3, 7, 8, 9, 5, 3, 6]])

# operations

In [177]:
a = np.random.randint(10,20,5)
a

array([16, 19, 17, 14, 17])

In [179]:
arr

array([0, 1, 2, 3, 3, 4, 5])

In [185]:
arr2 = np.random.randint(0,100,(10,10))
arr2

array([[ 5, 69,  9, 97, 97, 12,  5, 65,  3,  2],
       [13, 31, 60, 42, 62, 90, 31, 63, 88, 82],
       [45, 65, 28,  8, 12, 97, 65, 13, 59,  8],
       [18, 93, 97, 15, 97, 61, 67, 82, 14, 73],
       [71, 94, 21, 23, 94, 41, 19, 33, 98, 25],
       [72, 94, 78, 89, 76,  7, 58,  2, 63, 40],
       [92, 12, 74, 81, 35, 71, 10,  7, 94,  8],
       [22, 10, 27, 34, 75, 96, 80, 67, 23,  1],
       [43, 82, 64, 98, 61, 64, 45, 75, 11, 56],
       [ 8, 10, 27, 58, 35, 32, 25,  2, 70, 87]])

In [187]:
arr

array([0, 1, 2, 3, 3, 4, 5])

In [250]:
type(arr)

numpy.ndarray

In [189]:
arr[:]

array([0, 1, 2, 3, 3, 4, 5])

In [191]:
arr[4]

3

In [193]:
arr[0:4]

array([0, 1, 2, 3])

In [195]:
arr2[:]

array([[ 5, 69,  9, 97, 97, 12,  5, 65,  3,  2],
       [13, 31, 60, 42, 62, 90, 31, 63, 88, 82],
       [45, 65, 28,  8, 12, 97, 65, 13, 59,  8],
       [18, 93, 97, 15, 97, 61, 67, 82, 14, 73],
       [71, 94, 21, 23, 94, 41, 19, 33, 98, 25],
       [72, 94, 78, 89, 76,  7, 58,  2, 63, 40],
       [92, 12, 74, 81, 35, 71, 10,  7, 94,  8],
       [22, 10, 27, 34, 75, 96, 80, 67, 23,  1],
       [43, 82, 64, 98, 61, 64, 45, 75, 11, 56],
       [ 8, 10, 27, 58, 35, 32, 25,  2, 70, 87]])

In [197]:
arr2[0:5]

array([[ 5, 69,  9, 97, 97, 12,  5, 65,  3,  2],
       [13, 31, 60, 42, 62, 90, 31, 63, 88, 82],
       [45, 65, 28,  8, 12, 97, 65, 13, 59,  8],
       [18, 93, 97, 15, 97, 61, 67, 82, 14, 73],
       [71, 94, 21, 23, 94, 41, 19, 33, 98, 25]])

In [201]:
arr2

array([[ 5, 69,  9, 97, 97, 12,  5, 65,  3,  2],
       [13, 31, 60, 42, 62, 90, 31, 63, 88, 82],
       [45, 65, 28,  8, 12, 97, 65, 13, 59,  8],
       [18, 93, 97, 15, 97, 61, 67, 82, 14, 73],
       [71, 94, 21, 23, 94, 41, 19, 33, 98, 25],
       [72, 94, 78, 89, 76,  7, 58,  2, 63, 40],
       [92, 12, 74, 81, 35, 71, 10,  7, 94,  8],
       [22, 10, 27, 34, 75, 96, 80, 67, 23,  1],
       [43, 82, 64, 98, 61, 64, 45, 75, 11, 56],
       [ 8, 10, 27, 58, 35, 32, 25,  2, 70, 87]])

In [199]:
arr2[-5,-5]



7

In [203]:
arr2[-5,5]

7

In [205]:
arr2[-6,-6]

94

In [209]:
arr2[-6,6]

19

In [211]:
arr2

array([[ 5, 69,  9, 97, 97, 12,  5, 65,  3,  2],
       [13, 31, 60, 42, 62, 90, 31, 63, 88, 82],
       [45, 65, 28,  8, 12, 97, 65, 13, 59,  8],
       [18, 93, 97, 15, 97, 61, 67, 82, 14, 73],
       [71, 94, 21, 23, 94, 41, 19, 33, 98, 25],
       [72, 94, 78, 89, 76,  7, 58,  2, 63, 40],
       [92, 12, 74, 81, 35, 71, 10,  7, 94,  8],
       [22, 10, 27, 34, 75, 96, 80, 67, 23,  1],
       [43, 82, 64, 98, 61, 64, 45, 75, 11, 56],
       [ 8, 10, 27, 58, 35, 32, 25,  2, 70, 87]])

In [213]:
arr2[::-1]

array([[ 8, 10, 27, 58, 35, 32, 25,  2, 70, 87],
       [43, 82, 64, 98, 61, 64, 45, 75, 11, 56],
       [22, 10, 27, 34, 75, 96, 80, 67, 23,  1],
       [92, 12, 74, 81, 35, 71, 10,  7, 94,  8],
       [72, 94, 78, 89, 76,  7, 58,  2, 63, 40],
       [71, 94, 21, 23, 94, 41, 19, 33, 98, 25],
       [18, 93, 97, 15, 97, 61, 67, 82, 14, 73],
       [45, 65, 28,  8, 12, 97, 65, 13, 59,  8],
       [13, 31, 60, 42, 62, 90, 31, 63, 88, 82],
       [ 5, 69,  9, 97, 97, 12,  5, 65,  3,  2]])

In [215]:
arr2[::-2]

array([[ 8, 10, 27, 58, 35, 32, 25,  2, 70, 87],
       [22, 10, 27, 34, 75, 96, 80, 67, 23,  1],
       [72, 94, 78, 89, 76,  7, 58,  2, 63, 40],
       [18, 93, 97, 15, 97, 61, 67, 82, 14, 73],
       [13, 31, 60, 42, 62, 90, 31, 63, 88, 82]])

In [217]:
arr2[::-3]

array([[ 8, 10, 27, 58, 35, 32, 25,  2, 70, 87],
       [92, 12, 74, 81, 35, 71, 10,  7, 94,  8],
       [18, 93, 97, 15, 97, 61, 67, 82, 14, 73],
       [ 5, 69,  9, 97, 97, 12,  5, 65,  3,  2]])

In [219]:
arr2.max()

98

In [221]:
arr2.min()

1

In [223]:
arr2.mean()

49.13

In [227]:

arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [230]:
from numpy import *
a = array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [232]:
median(a)

3.0

In [236]:
arr.reshape(2,2)

ValueError: cannot reshape array of size 7 into shape (2,2)

In [238]:
arr

array([0, 1, 2, 3, 3, 4, 5])

In [252]:
arr3 = np.array([0,1,2,3,4,5])
arr3

array([0, 1, 2, 3, 4, 5])

In [254]:
type(arr3)

numpy.ndarray

In [256]:
arr3.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [258]:
arr3.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [260]:
arr3.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [262]:
arr3.reshape(1,5)

ValueError: cannot reshape array of size 6 into shape (1,5)

In [264]:
arr3.reshape(3,2,order='C')

array([[0, 1],
       [2, 3],
       [4, 5]])

In [268]:
arr3.reshape(3,2,order='F')

array([[0, 3],
       [1, 4],
       [2, 5]])

In [270]:
arr3.reshape(3,2,order='A')

array([[0, 1],
       [2, 3],
       [4, 5]])

In [278]:
arr3.reshape(3,2,order='K')

ValueError: order 'K' is not permitted for reshaping

In [280]:
arr3

array([0, 1, 2, 3, 4, 5])

In [282]:
arr3.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [284]:
arr3.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [286]:
arr3.reshape(3,3)

ValueError: cannot reshape array of size 6 into shape (3,3)

# indexing

In [302]:
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [308]:
row =4 
col = 5

In [310]:
row

4

In [313]:
col

5

In [315]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [317]:
mat[row,col]

45

In [319]:
mat[4,5]

45

In [321]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [323]:
col

5

In [325]:
col = 6

In [327]:
col

6

In [329]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [331]:
mat[1:col]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [335]:
mat[row,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [341]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [344]:
mat[:row]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [346]:
mat[row:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [350]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [348]:
mat[:col]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [352]:
mat[col:]

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [354]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [356]:
mat[8,:]

array([80, 81, 82, 83, 84, 85, 86, 87, 88, 89])

In [358]:
mat[:,-1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [360]:
mat 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [362]:
row

4

In [364]:
col

6

In [366]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [368]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [370]:
mat[1,4]

14

In [372]:
mat[1:4]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [374]:
mat[3:-3]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [376]:
mat[3,-3]

37

In [378]:
mat[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [380]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [382]:
mat[6:]

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [388]:
mat[6,:] #row & col 

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [386]:
mat[:,6]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [393]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [395]:
mat[5:7]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [397]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [399]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [401]:
mat[:4]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [403]:
mat[4:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [405]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [407]:
mat[::-6]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [410]:
mat[2:6]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [414]:
mat[2:6,2:4] #row & column methiod 2:6 row part and 2:4 indiates column part

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [416]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [418]:
mat[0,1]

1

In [424]:
mat[1,6]

16

In [422]:
mat[1:6]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [426]:
mat[1:]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [428]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [430]:
mat[3:5]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [434]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [432]:
mat[3,5]

35

In [436]:
mat[1:2,3:4]

array([[13]])

In [438]:
mat[2:3,2:3]

array([[22]])

In [440]:
mat[2:4,3:5]

array([[23, 24],
       [33, 34]])

# Masking

In [443]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [445]:
id(mat)

1793135209392

In [447]:
mat<50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [449]:
mat>50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [451]:
mat == 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [453]:
mat[mat==50]

array([50])

In [457]:
a1 = mat[mat<50]
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [461]:
a2 = mat[mat>50]
a2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [463]:
a4 = mat[mat==50]
a4

array([50])

In [465]:
mat>50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [467]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [469]:
a2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [473]:
a4

array([50])