In [1]:
import numpy as np


In [9]:
np.array([2,4,56,433,32,1]) # 1d array


array([  2,   4,  56, 433,  32,   1])

In [11]:
a = np.array([2,4,56,433,32,1]) 
print(a)


[  2   4  56 433  32   1]


In [13]:
type(a)

numpy.ndarray

In [21]:
#2d array # matrix
new = np.array([[45,36,46,37],[24,56,67,68]])
print(new)

[[45 36 46 37]
 [24 56 67 68]]


In [27]:
# 3D array
np.array([[2,3,4,5,5,],[23,45,67,67,78],[2536,4747,57,68,89],[34,89,90,56,78]])

array([[   2,    3,    4,    5,    5],
       [  23,   45,   67,   67,   78],
       [2536, 4747,   57,   68,   89],
       [  34,   89,   90,   56,   78]])

In [65]:
np.array([11,23,44], dtype=float)

array([11., 23., 44.])

In [67]:
np.array([11,223,33], dtype=bool) #here is True because python treats non zero

array([ True,  True,  True])

In [69]:
np.array([11,44,66], dtype=complex)

array([11.+0.j, 44.+0.j, 66.+0.j])

### arange

In [72]:
np.arange(1,25) # 1 = included & 25- last one got excluded

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [80]:
np.arange(1,25,3) #strides ...... alternate number

array([ 1,  4,  7, 10, 13, 16, 19, 22])

In [82]:
np.arange(-10,10)

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9])

In [86]:
np.arange(20,10) #always bigger value comes first in numpy

array([], dtype=int32)

In [88]:
np.arange(10,100,10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

# reshape

In [95]:
np.arange(1,11).reshape(5,2) #convert 5 rows and 2 columns

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [97]:
np.arange(1,20).reshape(2,5)

ValueError: cannot reshape array of size 19 into shape (2,5)

In [121]:
np.arange(1,21).reshape(2,10) #for short cut is 2*10

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [117]:
np.arange(1,13).reshape(4,3) #littlebit logic need

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [123]:
np.arange(1,13).reshape(3,4) #littlebit logic need

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# ones & zeros

In [130]:
# np.ones and np.zeros
np.ones((3,4)) #We have to mention tuple inside

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [134]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [136]:
np.zeros((3,6)) #by default is shows float 

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [138]:
# random()
np.random.random()

0.16590273908531095

In [142]:
np.random.random(3)

array([0.11234939, 0.35156237, 0.14490604])

In [148]:
np.random.random((3,4))

array([[0.41423265, 0.42611664, 0.28588711, 0.72905655],
       [0.99176913, 0.12933214, 0.6016891 , 0.07707899],
       [0.277381  , 0.92692946, 0.64289505, 0.97646245]])

In [205]:
np.random.rand(5)

array([0.25782459, 0.11873167, 0.55607393, 0.14798408, 0.44802363])

In [177]:
np.random.randint(2,4) # always print Middle and smaller # big number exclusive 

2

In [179]:
np.random.randint(2,7)

4

In [191]:
np.random.rand(2,5,4) #create a 2 layer with 5 rows and 4 columns

array([[[0.80338454, 0.30525808, 0.17347123, 0.45871963],
        [0.65135278, 0.56400456, 0.25834457, 0.8576633 ],
        [0.37056471, 0.94395054, 0.96592547, 0.20308514],
        [0.87651763, 0.7893947 , 0.94057888, 0.22142517],
        [0.03240045, 0.49183414, 0.00284839, 0.15744978]],

       [[0.98167839, 0.34370085, 0.90522709, 0.92877348],
        [0.76265345, 0.4696723 , 0.61148178, 0.13186702],
        [0.23390186, 0.88430005, 0.38944066, 0.86740659],
        [0.74020891, 0.30272516, 0.71035168, 0.09706693],
        [0.25883252, 0.8991778 , 0.82732306, 0.86781281]]])

In [193]:
np.random.randint(10,15,3)

array([11, 11, 13])

In [201]:
np.random.randint(10,40,(5,12))

array([[25, 35, 32, 38, 36, 38, 29, 22, 12, 19, 36, 16],
       [10, 30, 39, 27, 17, 23, 27, 20, 22, 25, 15, 15],
       [16, 10, 30, 17, 39, 19, 23, 14, 15, 21, 18, 36],
       [38, 25, 19, 22, 18, 34, 11, 25, 19, 37, 19, 38],
       [38, 38, 16, 36, 26, 16, 28, 11, 12, 16, 24, 19]])